### ISSUE TITLE
Estonian translations

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-cf7-plugin#15]
The idea was to provide translations through Wordpress.org, rather than providing Gettext files with the plugin.

Is it possible? And what needs to be done to get the plugin translated into Estonian?

**Comment by TomAbel** [comment]
>  1. For a plugin to be imported properly and take advantage of Wordpress language packs, it must have a text domain that matches its slug.

The text domain matches the slug for this plugin, so translation options will appear in https://translate.wordpress.org/projects/wp-plugins/smaily-for-contact-form-7
> 2. Additionally, if the plugin already ships language files (.mo), these will be imported into translate.wordpress.org.  
> 3. Once a plugin has been imported and the relevant language packs have been generated, plugins can remove the language files from their package (and from SVN).

https://make.wordpress.org/meta/handbook/documentation/translations/

I will make the translations and they can be reviewed via GitHub, later on they may be deleted.

**Comment by TomAbel** [comment]
Do you want to review translations by GitHub, commit, and later remove them or handle it all using translate.wordpress.org?

**Comment by kaittodesk** [comment]
All translations will end up being on translate.wordpress.org anyway and they can always be updated there. So I think there is no need for a separate review in GitHub.

**Comment by kaittodesk** [comment]
Plugin has been released to Wordpress.org - https://wordpress.org/plugins/smaily-for-contact-form-7/. Now it should be possible to translate the plugin using translate.wordpress.org.

**Comment by kaittodesk** [comment]
Looks like there is some sort of an issue with the project and we are not able to translate it in translate.wordpress.org.

When visiting the [project page](https://translate.wordpress.org/locale/et/default/wp-plugins/smaily-for-contact-form-7/) I get an error:
> This plugin is not properly prepared for localization (View detailed logs on Slack). If you would like to translate this plugin, please contact the author.

**Comment by kaittodesk** [comment]
Using translate.wordpress.org seems to be more hassle then I first anticipated. Each locale has its own set of language editors and they need to approve translations for the plugin.

In order to be efficient with translating the plugin we need to either become project language editors under each locale we wish to translate ourselves or just commit language files to Git. Latter is just easier to accomplish and maintain.

What do you think?

**Comment by TomAbel** [comment]
> What do you think?

I don't see the point of using `translate.wordpress`. Using `translate.wordpress.org` allows other translators to easily add translations, but I think the estonian translators are mostly dealing with the popular, 1M+ install plugins.

**Comment by TomAbel** [comment]
Closed with #26
